typedef enum {
    MACHINE_FAILURE = -10,
    INVALID_OPCODE = -8,
    INVALID_EFFECTIVE_ADDRESS = -7,
    UNIMPLEMENTED_INSTRUCTION = -6,
    FAILED_SEGBOUND_CHECK = -5,
    BAD_DECODE = -4,
    BUS_WRITE_FAILURE = -3,
    BUS_READ_FAILURE = -2,
    BAD_EXECUTION = -1,
    END_OF_PROGRAM = 0,
    EXECUTE_SUCCESS = 1,
    MACHINE_TURN_OFF = 2,
} ReturnCode;
